### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by crazyscientist**
* Backend: Use `psycopg2-binary` to skip compiling
* Frontend
  - Use new `suse-bootstrap5-theme`
  - Removed dummy schema entries
  - Do not use `this` in parameter binding
  - Added navbar

### CODE REVIEW

**Comment by commanderprice** [comment]
You have `file:suse-bootstrap5-theme` in package.json. Is that a link to local file?🤔

**Comment by crazyscientist** [comment]
> Is that a link to local file?

It is, because I was also editing the theme at the same time. But I did not intent to push this version :joy:

**Comment by commanderprice** [comment]
Oh, wow, everything is so green😅 Okay, seems to work, although I noticed that now when creating schema and adding attributes two last input fields are for some reason lower than the first one🤔 Not sure it was this way before, but that's not a big deal
image

**Comment by crazyscientist** [comment]
> Not sure it was this way before,

Me neither, I did not get that far today ...

**Pull request merged**
