### PR TITLE
Replaced response model for `general_routes.get_recent_*_changes`

### PR DESCRIPTION
**Pull request by crazyscientist**
Replaced `RecentChangeSchema` with `ChangeRequestSchema`

### CODE REVIEW

**Comment by commanderprice** [comment]
As I understand, `RecentChangeSchema` is a shorter version of `ChangeRequestSchema` which keeps only those fields which are used to display recent changes?

**Comment by crazyscientist** [comment]
Yes, but I thought it would be nice to have all the information from the `ChangeRequest` model available in the API response. This way we can present all the _meta information_ about a change without the need to fetch the details.

**Comment by commanderprice** [comment]
Ohh, you didn't add `RecentChangeSchema`, you deleted it😥 Will you take a look at failing tests?

**Comment by crazyscientist** [comment]
> Ohh, you didn't add `RecentChangeSchema`, you deleted it

Yes, I had the impression it would not be needed any longer.

> Will you take a look at failing tests?

I probably should.

**Pull request merged**
